### ISSUE TITLE
Несерьёзные проблемки

### ISSUE THREAD

**Issue by Dunamis4tw** [dedepete/Forgefier#1]
1) Если у программы не будет доступа к сайту она просто закроется без каких-либо уведомлений. Можно сделать простой messagebox с описанием проблемы.
2) Оформление не очень удобное, я бы даже сказал кривоватое. Его бы тоже получше сделать. Но, я так понимаю, это далеко не конченая версия и на интерфейс пока нет смыла тратить время? (На EN выглядит более менее хорошо)
3) Не знаю кто пользуется TABом в программах, но здесь они явно вразброс стоят :D
4) При установке в чистую папку программа всё скачивает нормально, но останавливается на launcher_profiles.json, т.к. его нет. На этом программа останавливается. Может научить её создавать этот файл?
5) Программе требуется Java, в новости на ru-minecraft.ru это не указано.
6) В новости написано:

> Один файл для всех версий.

Что не совсем верно, т.к. программа состоит не из одного файла. Одним из способов запихать всё в один файл, это самораспаковывающийся архив, который распаковывается в фоне во временную папку и запускает уже саму программу.

Это я не придираюсь, это я просто предлагаю, что можно изменить/исправить в программе, прошу меня понять.

Если что, я LeoganPro на сайте ru-minecraft.ru

**Comment by dedepete** [comment]
@Dunamis4tw спасибо за отзыв.
1. Я так и думал, что эту проблему кто-нибудь рано или поздно заметит!) Я уже работаю над ней. 
2. Да, это ещё черновая версия, но основная концепция уже определена. Если есть предложения по улучшению интерфейса, то очень хотелось бы их увидеть. 
3. Исправил. В следующей фиксации опубликую. 
4. По хорошему надо прерывать установку сразу же при отсутствии необходимой структуры файлов в папке Minecraft. Forgefier должен быть дополнением к лаунчерам, а не выполнять их работу (например, сейчас выполняется загрузка абсолютно всех библиотек для игры, хотя следует загружать только сжатые `.pack.xz`). 
5. Подразумевается, что Java уже должна быть установлена у конечного пользователя к моменту первого запуска программы, но лучше действительно дополнить этот момент. 
6. К релизу я планирую вшить LibraryUnpacker и библиотеки в исполняемый файл. Это уберёт абсолютно всё в один файл.

**Comment by dedepete** [comment]
Закрыл некоторые проблемы в 8d1a6c805bfb8f1862a40eb719b6d3e70b2a0cb9.
