### ISSUE TITLE
Вариант интерфейса

### ISSUE THREAD

**Issue by Dunamis4tw** [dedepete/Forgefier#2]
Вот мой вариант интерфейса этой программы:
![screen](https://user-images.githubusercontent.com/13050848/41738813-86cf4d96-75ac-11e8-9af1-9bc8aab38eb1.png)
Сделал на Delphi, т.к. с Visual Studio не дружу :D 
Вот исходники и exe, если что:
[Projects.zip](https://github.com/dedepete/Forgefier/files/2124944/Projects.zip)

Этот вариант далеко не идеальный, но как мне кажется он будет поудобней.
В меню есть пункт Расширенные настройки, который может убирать соответствующий GroupBox

**Comment by dedepete** [comment]
Мне понравился предложенный вариант. Интерфейс стал выглядеть намного свежее. 
![default](https://user-images.githubusercontent.com/1936922/41814269-5d24b7c4-7750-11e8-813a-291ef4bddf72.png)

**Comment by dedepete** [comment]
Closed in 09fc69ca00f6e46489a62bc1e59a7940ca776167.
